language: node_js
node_js:
- '10'
- '8'
- '6'
after_script:
- nyc report reporter=text-lcov | codeclimate-test-reporter
deploy:
  provider: npm
  email: wouter.dullaert@gmail.com
  api_key:
    secure: "rL5NQkxC2kQFMSr+5x1BCFWvDtBewZqymvGncMRL7XDvlAYpachtdjNbzCJKbd68DjJbU3wR9jYVNOTyvDf064Psj35kujCzBtZqhTY8hvb60WHJLhWdPODroAy4UMBF/67KG3ccrK21sFaEkPdLwRVg+XMPTopZWDXudhv3FeCwr9c39HuN5pPxhEAkfApug37nHhwwgH5DvGw1XTnYkhjWEMYDLRv59AzuBrLZaIc/oaQkP6O4QmiDE7N3X+QahF3Kk/isBDLVjWBrxmXwHDqaa3x2HprknqJOuhTRv3hv6Q8iolCDy17DIM+tCB8PrS6Zh476s8Zy/lLwaosZoZ9YI6/tfQr9/DY4iz9M32kv5Kw5TFZf0/Tg4a5RrD1BLUMoSDIMNcTs686t0GMQ3VGYHmT2ojIt55YbDWASJolognm+OrBF5ictc6ZZzc54bUf/eRZHXS8yZwBuyHvyVy74x2EdLe3NmgpELcYXQEMdv+Ig4MxYdkqAjpQxhDLMO83UxRXMa7yVjzD9Ayj+jDTg2dgvm70RpWucqT9laf8v/jDC2H/M9FJ9CCLUCkzBsqcknV54LYIc28nYBFl7Uc7PKn+x+i0e8G7/mYrkr9kdpCYQXjr+dR4FjFjowF4L7fbst7t8cL2qST+5dpFaXwSc6GmTxXZ01NmZsVG0Dfg="
  skip_cleanup: true
  on:
    tags: true
    node: '8'
addons:
  code_climate:
    repo_token: c335973c213928c6367d34f20229d7c68f1fa0afa9420e962be0728b8a5461d7
